backend:
  branch: main
  name: git-gateway
collections:
- create: true
  description: This is what we do best. Writing blog posts.
  fields:
  - label: Title
    name: title
    widget: string
  - label: Date
    name: date
    widget: date
  - label: Description
    name: description
    required: false
    widget: markdown
  - label: Body
    name: body
    required: false
    widget: markdown
  - collapsed: true
    fields:
    - label: Description
      name: description
      required: false
      widget: markdown
    - label: Image
      name: image
      required: false
      widget: image
    - label: Canonical URL
      name: canonical
      required: false
      widget: string
    label: SEO
    name: seo
    widget: object
  filter:
    field: exclude_collection
  folder: content/en/post
  label: Posts
  label_singular: Post
  name: posts
  preview_path: blog/{{slug}}
  sortableFields:
  - title
local_backend: true
media_folder: static/uploads
public_folder: /uploads
show_preview_links: true
slug:
  clean_accents: true
  encoding: ascii
  sanitize_replacement: '-'
use_graphql: true
